<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
	
	<div class="authorization-link switcher" id="authorization-top-link"> <?php /* data-label="<?php echo $block->escapeHtml(__('or')); ?>" */ ?>
		<div class="actions dropdown options switcher-options">
			<div class="action toggle switcher-trigger" id="authorization-trigger">
				<?php echo $block->escapeHtml($block->getLabel()); ?>
			</div>
			<div style="display:none;" id="cdz-login-form-dropdown" class="cdz-login-form-dropdown dropdown switcher-dropdown"  data-mage-init='{"dropdownDialog":{
						"appendTo":"#authorization-top-link > .options",
						"triggerTarget":"#authorization-trigger",
						"closeOnMouseLeave": false,
						"triggerClass":"active",
						"parentClass":"active",
						"buttons":null}}'>
				<?php if(!$block->isLoggedIn() ): ?>				
					<?php echo $block->getChildHtml('customer_form_login_mini') ?>
				<?php else: ?>
					<?php echo $block->getChildHtml('customer') ?>
				<?php endif ?>				
			</div>
		</div>
	</div>


