<?php
$qsHelper = $this->helper('Codazon\QuickShop\Helper\Data');
$itemClass = $qsHelper->getConfig('quickshop/general/item_class');
$target = $qsHelper->getConfig('quickshop/general/target');
$autoAddButtons = $qsHelper->getConfig('quickshop/general/auto_add_buttons');
?>
<div id="quickshop" class="quickshop-modal">
	<div class="content-wrap">
    	<div class="qs-loading-wrap" style="display:none;">
        	<div class="qs-loader"><img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php echo __('Loading...') ?>" /></div>
		</div>
        <div class="qs-content qs-main" style="display:none;"></div>
    </div>
</div>
<script type="text/x-magento-init">
{
	"body":{
		"Codazon_QuickShop/js/quickshop":{
			"baseUrl": "<?php echo $qsHelper->getBaseUrl() ?>",
			"qsLabel": "<?php echo $qsHelper->getQuickShopLabel() ?>",
			"itemClass": "<?php echo (!empty($itemClass))?$itemClass:"" ?>",
			"target": "<?php echo (!empty($target))?$target:".product-item-info"; ?>",
			"autoAddButtons":<?php echo ($autoAddButtons==1)?"true":"false" ?>
			}
	}
}
</script>