<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>


<div class="cdz-popup-content" style="display:none">
<!-- popup-cotent -->
    <?php echo $block->getChildHtml('block.popup.container') ?>
</div>
<script>
require([
        'jquery',
        'mage/cookies',
        'modal',
        'domReady!'
],function($){
   	if(!$.mage.cookies.get("fastest-popup")){
                $.mage.cookies.set('fastest-popup', 'true');
        	$('.cdz-popup-content').modal({
                        autoOpen: true,
                        wrapperClass: "modals-wrapper cdz-popup-wrapper"
                });
  	}
});
</script>

