<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<?php echo $block->getChildHtml('leftmenu') ?>
		</div>
		<div class="col-sm-18">
			<?php echo $block->getChildHtml('topslideshow') ?>
			<?php echo $block->getChildHtml('breadcrumbs') ?>
		</div>
	</div>
</div>
