<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if($block->customerLoggedIn()): ?>
    <div class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"              
              data-bind="scope: 'customer'">
            <span data-bind="text: customer().fullname"></span>            
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <?php if($block->getChildHtml()):?>
        <ul class="customer-links">
            <?php echo $block->getChildHtml();?>
        </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>
