<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
	<div class="success-title">
		<p><span class="success-title-icon">icon</span></p>
		<p><span><?php echo __('Thank you!') ?></span></p>
	</div>
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a class="order-id" href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

	<div class="primary">
		<a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
	</div>
	<div class="success-bottom">
		<p><?php echo __('You can track your order status by creating an account.') ?></p>
		<div class="primary">
			<a class="action primary continue" href="<?php echo $this->getUrl('customer/account/create') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an account') ?></span></a>
		</div>
		
	</div>
</div>
