<?php
use Magento\Framework\App\Action\Action;
?>

<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_productSize = $_productCollection->count();
$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');
?>
<?php if (!$_productSize): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $image_hover = 'category_page_grid_hover';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $classid = $block->getBlockId();//uniqid();//md5(json_encode($block->getData()));    
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();

    $row = 2;
    $wLHelper = $this->helper('Magento\Wishlist\Helper\Data'); //getWishlistItemCollection
    global $wLItemArray;
	if( empty($wLItemArray) ){
		$wLCollection = $wLHelper->getWishlistItemCollection();
		$wLItemArray = [-1];
		foreach($wLCollection as $wLItem){
			$wLItemArray[] = $wLItem->getProductId();	
		}
	}
    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php if ($title):?>
		<div class="cdz-block-title">
		    <h2 class="b-title"><span><?php /* @escapeNotVerified */ echo $title; ?></span></h2>
		</div>
		<?php endif ?>
		<div class="block-content <?php echo $classid ?>">
			<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
				<?php $iterator = 0; ?>
				<div class="products list items product-items same-height <?php echo $block->getData('show_slider') ? 'cdz-slider' : '' ?>"
					<?php if($block->getData('show_slider')) : ?>
					<?php $slider_item =  $block->getData('slider_item') > 0 ?  $block->getData('slider_item') : 6 ?>
						data-items="<?php echo $slider_item ?>"
						data-items-0="2"
						data-items-480="2"
						data-items-768="<?php echo abs($slider_item-1) ?>"		            	
						data-items-1024="<?php echo $slider_item ?>"	
						data-items-1280="<?php echo $slider_item ?>"
						data-items-1440="<?php echo $slider_item ?>"
						data-loop="false" 
						data-margin="20"
					<?php endif; ?>
				>
				    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				    <?php foreach ($_productCollection as $_product): ?>
				    <?php if ($iterator%$row==0 || $iterator == 0): ?>
					<div class="item-slider"> 
				        <?php endif; ?>
					<div class="item product product-item">
				         <div class="product-item-info" data-container="product-grid">
				        	<div class="product-info-top">
					            <?php
					            $productImage = $block->getImage($_product, $image);
					            $productHoverImage = $block->getImage($_product, $image_hover);
					            if ($pos != null) {
					                $position = ' style="left:' . $productImage->getWidth() . 'px;'
					                    . 'top:' . $productImage->getHeight() . 'px;"';
					            }
					            ?>
					            <?php // Product Image ?>
					           				           
				               <?php if($block->isShow('thumb')): ?>
					            <div class="cdz-hover-section">
	                                <div class="cdz-product-top">
	                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
	                                        <span class="main-image">
												<?php echo $productImage->toHtml(); ?>
											</span>
											<span class="hover-image">
												<?php echo $productHoverImage->toHtml(); ?>
											</span>
	                                    </a>
	                                </div>
									<div class="cdz-product-wishlist">
										<?php if($block->isShow('addto')): ?>
										<?php $inWLClass = ( in_array($_product->getId(),$wLItemArray) )?'in-wishlist':''; ?>										
										<div class="actions-secondary show-tooltip" data-role="add-to-links" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>">
	                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
	                                            <a href="#"
	                                               class="action towishlist <?php echo $inWLClass ?>"
	                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
	                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
	                                               data-action="add-to-wishlist"
	                                               role="button">
	                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
	                                            </a>
	                                        <?php endif; ?>
	                                    </div>
	                                    <?php endif ?>
									</div>
									
									<?php $labelHelper->showLabel($_product) ?>                                								
	                            </div>
					            <?php endif ?>   
				        	</div>
				            <div class="product details product-item-details">
				                <?php
				                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
				                ?>
				                <?php if($block->isShow('name')): ?>
				                <strong class="product name product-item-name">
				                    <a class="product-item-link"
				                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
				                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				                    </a>
				                </strong>
				                <?php endif ?>
				                <?php if($block->isShow('description')): ?>
			                        <div class="product description product-item-description">
			                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
			                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
			                               class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
			                        </div>
				                <?php endif; ?>
				                <div class="price-review">
				                	<?php if($block->isShow('price')): ?>
					                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
					                <?php endif ?>
					                <?php if($block->isShow('review')): ?>
					                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
					                <?php endif ?>					                
				                </div>
				                <?php echo $block->getProductDetailsHtml($_product); ?>
				     
				                <div class="product-bottom">
                                	<div class="product-buttons-container">
                                    	<div class="product-buttons-inner">
                                    	<?php echo $this->helper('Codazon\QuickShop\Helper\Data')->getQuickShopButton($_product); ?>
				                    	<?php if($block->isShow('addtocart')): ?>
				                            <?php if ($_product->isSaleable()): ?>
				                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
				                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
				                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
				                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
				                                    <?php echo $block->getBlockHtml('formkey')?>
				                                    <button type="submit"
				                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
				                                            class="action tocart primary">
				                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
				                                    </button>
				                                </form>
				                            <?php else: ?>
				                                <?php if ($_product->getIsSalable()): ?>
				                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
				                                <?php else: ?>
				                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
				                                <?php endif; ?>
				                            <?php endif; ?>
				                        
				                        <?php endif ?>
				                        <?php if($block->isShow('addto')): ?>
				                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>				                            
				                            <?php
				                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
				                            ?>
				                            <a href="#"
				                               class="action tocompare"
				                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				                               role="button">
				                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
				                            </a>
				                        </div>										
				                        <?php endif ?>										
										</div>
				                    </div>
				                   
				                </div>
				            </div>
				        </div>
			         </div>
					<?php if ( ($iterator+1)%$row==0 || $iterator+1==$_productSize ): ?>
						</div>
					<?php endif; ?>
				        <?php $iterator++; ?>
				    <?php endforeach; ?>
				</div>
			</div>
			<?php echo $block->getToolbarHtml() ?>
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			<?php endif; ?>
		</div>
	</div>	
<?php endif; ?>
