<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@codazon.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Codazon\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $height = 620;
    $width = 840;
    $helper = $this->helper('Magefan\Blog\Helper\Image');
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
    <div class="post-image cdz-left">
        <a href="<?php echo $_postUrl ?>">                
             <img class="img-responsive" width="<?php echo $width ?>" height="<?php echo $height ?>" src="<?php echo $helper->init($_post->getPostImage())->resize($width,$height); ?>" />
        </a>
        <div class="blog-date"><?php echo $block->getPostedOn('F d, Y'); ?></span></div>
    </div>
    <div class="post-details cdz-right">
        <div class="post-header">

            <div class="post-title-holder clearfix">
                <h2 class="post-title">
                    <a class="post-item-link"
                       href="<?php echo $_postUrl ?>">
                        <?php echo $_postName; ?>
                    </a>
                </h2>

                <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                    <a class="addthis_button_facebook"></a>
                    <a class="addthis_button_twitter"></a>
                    <a class="addthis_button_email"></a>
                    <a class="addthis_button_compact"></a>
                </div>
            </div>

            <?php echo $this->getInfoHtml() ?>
        </div>

        <div class="post-content">
            <div class="post-description clearfix">
                <?php
                		$descLength = 250;
				$desc = $block->getShortContent();
				if(strlen($desc)> $descLength ) { 
					$strCutDesc = substr($desc, 0, $descLength);
					$desc = substr($strCutDesc, 0, strrpos($strCutDesc, ' ')).'&hellip;';
				}
				$desc = $this->stripTags($desc,null,true);
			?>
			<?php echo $desc; ?>
                
            </div>
			<a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"
			   >
			   <?php echo __('Continue Read') ?>
			</a>
        </div>
    </div>
    <div class="post-footer">

    </div>
</li>
