<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@codazon.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Codazon\Blog\Block\Post\Info
 */
?>

<?php $_post = $block->getPost() ?>

<div class="post-info clear">    
    <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
    <div class="item post-categories">
        <span class="label"><?php echo __('Categories:') ?></span>
        <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
            <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
            <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
        <?php } ?>
    </div>
    <?php } ?>
</div>
