<?php
use Magento\Framework\App\Action\Action;
?>

<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$uniqId = uniqid('block_');
?>
<script>
var data_<?php echo $uniqId ?> = <?php echo json_encode($block->getData()) ?>;
</script>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $classid = md5(json_encode($block->getData()));
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$wLHelper = $this->helper('Magento\Wishlist\Helper\Data'); //getWishlistItemCollection
	$uniqId = uniqid('block_');
	global $wLItemArray;
	if( empty($wLItemArray) ){
		$wLCollection = $wLHelper->getWishlistItemCollection();
		$wLItemArray = [-1];
		foreach($wLCollection as $wLItem){
			$wLItemArray[] = $wLItem->getProductId();	
		}
	}
    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>" id="<?php echo $uniqId ?>">
		<?php if ($title):?>
		<div class="block-title">
		    <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
		</div>
		<?php endif ?>
		<div class="block-content <?php echo $classid ?>">
			<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
				<?php $iterator = 1; ?>
				<ol class="products list items product-items">
				    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				    <?php foreach ($_productCollection as $_product): ?>
				        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
				        <div class="product-item-info" data-container="product-grid">
				            <?php
				            $productImage = $block->getImage($_product, $image);
				            if ($pos != null) {
				                $position = ' style="left:' . $productImage->getWidth() . 'px;'
				                    . 'top:' . $productImage->getHeight() . 'px;"';
				            }
				            ?>
				            <?php if($block->isShow('thumb')): ?>
				            <div class="cdz-hover-section">
                                <div class="cdz-product-top">
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                        <?php echo $productImage->toHtml(); ?>
                                    </a>
                                </div>
								<div class="cdz-product-wishlist">
									<?php if($block->isShow('addto')): ?>
									<?php $inWLClass = ( in_array($_product->getId(),$wLItemArray) )?'in-wishlist':''; ?>
									<div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               class="action towishlist <?php echo $inWLClass ?>"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                    <?php endif ?>
								</div>
                                <div class="cdz-product-bottom">
                                	<div class="cdz-buttons-container">
                                        <?php echo $this->helper('Codazon\QuickShop\Helper\Data')->getQuickShopButton($_product); ?>
										<?php if($block->isShow('addtocart')): ?>
                                            <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                            <?php endif ?>
                                        <?php endif ?>
										<?php if($block->isShow('review')): ?>
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
										<?php endif ?>
                                    </div>
                                </div>
                            </div>
				            <?php endif ?>
				            <div class="product details product-item-details">
				                <?php
				                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
				                ?>
				                <?php if($block->isShow('name')): ?>
				                <strong class="product name product-item-name">
				                    <a class="product-item-link"
				                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
				                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				                    </a>
				                </strong>
				                <?php endif ?>

				                <?php if($block->isShow('price')): ?>
			                	<?php echo $block->getProductPrice($_product) ?>
				                <?php endif ?>
                                
				                <?php echo $block->getProductDetailsHtml($_product); ?>
				                
                                <div class="product-item-inner">
				                    <div class="product actions product-item-actions" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
				                    <?php if($block->isShow('description')): ?>
				                        <div class="product description product-item-description">
				                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
				                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>" class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
				                        </div>
				                    <?php endif; ?>
                                    </div>
				                </div>
                                
				            </div>
				        </div>
				        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				    <?php endforeach; ?>
				</ol>
			</div>
			<?php echo $block->getToolbarHtml() ?>
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			<?php endif; ?>
			<div class="ajax-load-wrapper">
				<div class="ajax-load-button">
					<a href="javascript:void(0)" class="btn cdz-ajax-trigger">
						<?php echo __('Load more') ?>
					</a>
					<div class="ajax-loader" style="display:none;"><?php echo __('Loading...') ?></div>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>
<script type="text/x-magento-init">
{
	"#<?php echo $uniqId ?>":{
		"Codazon_ProductFilter/js/ajaxload":{
			"ajaxUrl": "<?php echo $this->getUrl('productfilter/index/ajaxLoad') ?>",
			"currentUrl": "<?php echo $this->getUrl() ?>",
			"jsonData": <?php echo json_encode($block->getData()) ?>
		}
	}
}
</script>